import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        surface:                   '#fbf9fa',
        'surface-dim':             '#dbd9db',
        'surface-bright':          '#fbf9fa',
        'surface-container-lowest':'#ffffff',
        'surface-container-low':   '#f5f3f4',
        'surface-container':       '#f0edee',
        'surface-container-high':  '#eae7e9',
        'surface-container-highest':'#e4e2e3',
        'on-surface':              '#1b1b1d',
        'on-surface-variant':      '#44474c',
        'inverse-surface':         '#303032',
        'inverse-on-surface':      '#f2f0f1',
        outline:                   '#74777d',
        'outline-variant':         '#c4c6cc',
        'surface-tint':            '#525f71',
        primary:                   '#000000',
        'on-primary':              '#ffffff',
        'primary-container':       '#0f1c2c',
        'on-primary-container':    '#778598',
        'primary-fixed':           '#d6e4f9',
        'primary-fixed-dim':       '#bac8dc',
        'on-primary-fixed':        '#0f1c2c',
        'on-primary-fixed-variant':'#3a4859',
        'inverse-primary':         '#bac8dc',
        secondary:                 '#595f66',
        'on-secondary':            '#ffffff',
        'secondary-container':     '#dde3eb',
        'on-secondary-container':  '#5f656c',
        'secondary-fixed':         '#dde3eb',
        'secondary-fixed-dim':     '#c1c7cf',
        'on-secondary-fixed':      '#161c22',
        'on-secondary-fixed-variant':'#41474e',
        tertiary:                  '#000000',
        'on-tertiary':             '#ffffff',
        'tertiary-container':      '#0d1c2d',
        'on-tertiary-container':   '#768599',
        'tertiary-fixed':          '#d4e4fa',
        'tertiary-fixed-dim':      '#b9c8de',
        'on-tertiary-fixed':       '#0d1c2d',
        'on-tertiary-fixed-variant':'#39485a',
        error:                     '#ba1a1a',
        'on-error':                '#ffffff',
        'error-container':         '#ffdad6',
        'on-error-container':      '#93000a',
        background:                '#fbf9fa',
        'on-background':           '#1b1b1d',
        'surface-variant':         '#e4e2e3',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm:  '0.125rem',
        md:  '0.25rem',
        lg:  '0.25rem',
        xl:  '0.5rem',
        full:'9999px',
      },
      spacing: {
        unit:              '4px',
        gutter:            '16px',
        'margin-mobile':   '16px',
        'margin-desktop':  '32px',
        'container-max':   '1440px',
      },
      fontFamily: {
        sans:  ['var(--font-inter)', 'system-ui', 'sans-serif'],
        mono:  ['var(--font-jetbrains)', 'monospace'],
      },
      fontSize: {
        'headline-lg':   ['32px', { lineHeight:'1.2',  letterSpacing:'-0.02em', fontWeight:'700' }],
        'headline-md':   ['24px', { lineHeight:'1.3',  letterSpacing:'-0.01em', fontWeight:'600' }],
        'headline-sm':   ['18px', { lineHeight:'1.4',  letterSpacing:'0',       fontWeight:'600' }],
        'body-lg':       ['16px', { lineHeight:'1.5',  fontWeight:'400' }],
        'body-md':       ['14px', { lineHeight:'1.5',  fontWeight:'400' }],
        'body-sm':       ['12px', { lineHeight:'1.4',  fontWeight:'400' }],
        'technical-code':['13px', { lineHeight:'1.2',  fontWeight:'500' }],
        'label-caps':    ['11px', { lineHeight:'1',    letterSpacing:'0.05em',  fontWeight:'700' }],
      },
      maxWidth: {
        'container': '1440px',
      },
    },
  },
  plugins: [],
};

export default config;
